### PR TITLE
0.8.x support

### PR DESCRIPTION
**Pull request by FolkvangrForgent**
This patch works for me for 0.8.6. I have not tested it on other versions. It looks like the the way to find the config button was changed and so I changed the find function but it should default to the old method if it found nothing so it should be backwards compatible.

### CODE REVIEW

**Comment by dirusulixes** [comment]
When testing this PR I do get the menu to render,  but I get an error when trying to set the token hex size

```
foundry.js:8755 Error: [CQmOF9R1AsnERDvJ] TokenData width "1" is not a positive number
    at TokenData._validateField (data.mjs:376)
    at TokenData.validate (data.mjs:267)
    at ClientDatabaseBackend._preUpdateDocumentArray (foundry.js:8752)
    at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:8714)
    at ClientDatabaseBackend.update (backend.mjs:153)
    at async Function.updateDocuments (document.mjs:365)
    at async TokenDocument5e.update (document.mjs:447)
    ```

**Comment by FolkvangrForgent** [comment]
@dirusulixes 
Can you please provide more information about what system and or modules you may be using so I can test based on that. I currently am using the pf2e system and do not encounter that error.

**Comment by FolkvangrForgent** [comment]
Update with a fix to the problem that is throwing the error. I don't see how I didn't run into this earlier but looks like token no longer wants strings for number data, I feel like this change may break backwards compatibility, although I don't know how important backwards compatibility is for module development and if foundry versions have a support timeline or if only the current version is supported.

**Comment by Ourobor** [comment]
Alright, I've finally found the time to dig out my old test vms off my old hard disk and look into testing. I'll check previous versions at the same time. I'm not too concerned with very old versions really. I'll just tag this current version so anyone who wants to use older versions of foundry can use it, but it'd be nice if it could work with ~0.7.10ish for those who don't want to update to 0.8.6 yet. I'll test it out and let you know how the changes fair with the older versions on my test vm.

**Comment by FolkvangrForgent** [comment]
I think I might want to close this pull as I am still experiencing a fair amount of issues with my fixes than need to be addressed before It should be pulled into the main branch, my bad for not fully addressing these before  creating a pull request.

**Comment by Ourobor** [comment]
I've found one issue. I'm not sure if it's an issue with 0.8.6 or your changes(or my linux vm). If I open the token config dialog, change the size of a token and drag it, it messes up the token's art, reverting back to the size and location of it previously. It appears to be an issue with its height and width properties since the art scaling doesn't change. I'm going to check older versions with the older version of the module to see if it's an issue.

**Comment by Ourobor** [comment]
> 
> 
> I think I might want to close this pull as I am still experiencing a fair amount of issues with my fixes than need to be addressed before It should be pulled into the main branch, my bad for not fully testing and addressing these before creating a pull request.
> 
> It currently has issues working without drag ruler that I have not addressed

Eh, leave it open. As long as you're intending to continue working on it, it's better to leave it open and continue working. I also want this compatibility and it's helpful to coordinate efforts. I think?

**Comment by FolkvangrForgent** [comment]
Yeah I intend to keep working on this to try and get it working so I'll leave it up.

**Comment by Ourobor** [comment]
Alright. I'm going to go work on getting the other PR closed and once that's wrapped up, I'll loop on back here and see what I can do to help. Sorry again for taking so long to actually test your PR :/

**Comment by FolkvangrForgent** [comment]
Current encountered issues that still need to be fixed:

- [ ] moving the token with the config open causes the token image to revert. Is the desired behavior to be to not be able to move the token or to fix scale reverting.
- [ ] changing the size of the token does not cause it to snap to the hex grid.
- [ ] dirusulixes mentioned the presets by size are not pre-populated.

**Comment by dirusulixes** [comment]
Just to say the the latest version of the PR does show the presets. The main issue of sizes 2+ not snapping to the hex grid remains. Btw, drag ruler does show the correct hex size for the token when dragging it.

**Comment by Ourobor** [comment]
I apologize for not getting back to this earlier.

My current plan to move forward is to create a new branch (086Support) and merge all currently open PRs into that branch so we can have all progress in one place and so I can also add fixes I've noticed as well without being some weird mess of confusing pull requests. I'm also working on making a tag for 0.7.x stuff so the legacy code is still available for people running old foundry when 086Support eventually merges into master/main

**Comment by Ourobor** [comment]
All changes have been merged into 086Support. If you have more changes, please open a new PR against that branch. Given that it's a development branch, it should be a lot easier to merge in changes since the burden isn't on you to make everything perfect.

Thank you for your assistance so far!

**Comment by FolkvangrForgent** [comment]
Awesome yeah if I manage to fix anything else I'll submit a PR to that branch.

**Pull request closed without merging**
